name: web_game_studio
description: Mobile HTML CSS JS editor
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  shared_preferences: ^2.5.3
  code_text_field: ^1.1.0
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  flutter_foreground_task: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
